# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-06-05 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='姓名')),
                ('department', models.CharField(max_length=30, verbose_name='部门')),
                ('state', models.CharField(max_length=15, verbose_name='状态')),
                ('sex', models.CharField(max_length=3, verbose_name='性别')),
                ('tel', models.CharField(max_length=15, unique=True, verbose_name='电话')),
                ('duty', models.CharField(max_length=30, verbose_name='职位')),
                ('education', models.CharField(max_length=15, verbose_name='学历')),
                ('card', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='身份证')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
    ]
