# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-06-25 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=50, verbose_name='流程')),
                ('content', models.TextField(max_length=50, verbose_name='内容')),
                ('file', models.ImageField(null=True, upload_to='file_process/')),
                ('ceo_check', models.CharField(max_length=10, null=True)),
                ('cto_check', models.CharField(max_length=10, null=True)),
                ('ceo_content', models.TextField(max_length=50, null=True)),
                ('cto_content', models.TextField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'process',
            },
        ),
    ]
