# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-06-26 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_process_cate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='ceo_check',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='cto_check',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
