# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-06-24 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='姓名')),
                ('pwd', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_admin', models.IntegerField(null=True)),
                ('add_staff', models.IntegerField(null=True)),
                ('up_file', models.IntegerField(null=True)),
                ('show_file', models.IntegerField(null=True)),
                ('check_staff', models.IntegerField(null=True)),
                ('check_operation', models.IntegerField(null=True)),
                ('check_office', models.IntegerField(null=True)),
                ('sta_staff', models.IntegerField(null=True)),
                ('sta_opration', models.IntegerField(null=True)),
                ('sta_office', models.IntegerField(null=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.Admins')),
            ],
            options={
                'db_table': 'permission',
            },
        ),
    ]
