# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-06-24 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='add_admin',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='add_staff',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='check_office',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='check_operation',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='check_staff',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='show_file',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='sta_office',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='sta_opration',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='sta_staff',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='up_file',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
