# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-06-23 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='age',
            field=models.IntegerField(verbose_name='车龄'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='sites',
            field=models.IntegerField(verbose_name='座位'),
        ),
    ]
